//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP171206_kitapStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int Id { get; set; }
        public string UyeAdi { get; set; }
        public string UyeSoyadi { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
    }
}
